package control;

public enum GameStatus {
    CREDITS_SCREEN,
    GAME_OVER,
    MISSION_PASSED,
    MULTIPLAYER_HOST,
    MULTIPLAYER_JOIN,
    MULTIPLAYER_LOBBY,
    OUT_OF_TIME,
    RUNNING,
    START_SCREEN,
}
